package sys

import mock "github.com/stretchr/testify/mock"

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: to, subject, html, plain, data
func (_m *MockMailer) Send(to string, subject string, html string, plain string, data interface{}) error {
	ret := _m.Called(to, subject, html, plain, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, interface{}) error); ok {
		r0 = rf(to, subject, html, plain, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func NewMockMailer() *MockMailer {
	return new(MockMailer)
}
