package mail

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: to, message, data
func (_m *MockMailer) Send(to string, message Message, data interface{}) error {
	ret := _m.Called(to, message, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, Message, interface{}) error); ok {
		r0 = rf(to, message, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetFrom provides a mock function with given fields: _a0
func (_m *MockMailer) SetFrom(_a0 string) Mailer {
	ret := _m.Called(_a0)

	var r0 MockMailer
	if rf, ok := ret.Get(0).(func(string) MockMailer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MockMailer)
		}
	}

	return &r0
}

func NewMockMailer() *MockMailer {
	return new(MockMailer)
}
